### ISSUE TITLE
NodeJS application crashes at startup with SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by uluhonolulu** [ipld/js-ipld#245]
- **Version**: 0.25.2
- **Platform**: 64bit Windows
- **Subsystem**:

#### Description: NodeJS application crashes at startup with `SyntaxError: Unexpected token *`:

```
d:\Projects\my-project\node_modules\ipld\src\index.js:89
    const generator = async function * () {
                                     ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
...
    at Object.<anonymous> (d:\Projects\my-project\node_modules\ipfs\src\core\index.js:4:14)
...
    at Object.<anonymous> (d:\Projects\my-project\server\ipfs\routes.js:13:14)
```

#### Steps to reproduce the error:
Here's my code: 
```
const IPFS = require('ipfs')
```

**Comment by vmx** [comment]
It sounds like you are using a too old version of Node.js. Can you try it again with Node.js >=10?

**Comment by uluhonolulu** [comment]
@vmx thanks, it worked!
